### ISSUE TITLE
Is `jar-mod` a feature to be developed or something else?

### ISSUE THREAD

**Issue by yihleego** [lucasluqui/KnightLauncher#35]
Hi Lucas, 

I found that `/code-mods/*.jar` was defined in the project, but it doesn't seem to work now. 
Do you have any plans for the future?

https://github.com/lucasluqui/KnightLauncher/blob/e13ba029ec211150b26134cf40144ca374c7bb5b/src/main/java/com/lucasallegri/launcher/mods/ModLoader.java#L37-L46

I'm interested in developing jar mods that modify bytecode at runtime (No hacking at all). 
But I'm not sure if this is a risk to your project or user's account.

**Comment by lucasluqui** [comment]
Heya. It's in my plans to implement a system to merge the contents of files in `.../code-mods/` with either projectx-pcode.jar/projectx-config.jar as needed thus enabling modification of compiled .class files.

This feature is half baked at the moment (the functionality is partly there and was used for the recent Connection settings, giving the launcher the ability to modify config.jar with it's own deployment.properties file) but it still needs to be way more dynamic to accept user generated content.

Hope the answer was clear and wish you a great day!

**Comment by yihleego** [comment]
Thanks for your answer.

I found a way to load mods without modifying any original file.
And I will share it with you when I have some new progress.
