### ISSUE TITLE
Question: What are the merits of each java listed in the launcher?

### ISSUE THREAD

**Issue by HealerLFG** [lucasluqui/KnightLauncher#39]
At the time of this posting, there are three listings for replacing SK's java version:

- Java 7 (7u80) (Recommended)
- Java 8 (8u202)
- Java 8 (8u251)

What is the reason that 7u80 is the recommended version, and for what use-cases would the other two be better?

**Comment by lucasluqui** [comment]
Heya.

In the past (<1.7) Knight Launcher used to default to 8u251 when it came to patching Java VMs as it was -at the time- the most stable release we knew of.

Once 1.7 was tested internally we realized 7u80 had the best performance out of all three and at the same time just as stable or better. While 8u251 was generally the best option there were some cases where going for 8u202 -an older release of Java 8- or 7u80 -straight up a major release downgrade- helped fix crash issues present when attempting a launch using 8u251.

After 7u80 became the recommended VM version and with the introduction of the other two options we drastically reduced the amount of crash reports.

I hope this clears up your question.
Cheers!
