### ISSUE TITLE
Doesn't Start the game

### ISSUE THREAD

**Issue by Ahmedhejazy747** [lucasluqui/KnightLauncher#49]
So, basicly just in the title it doesn't start the game
i downloaded the launcher, readed the README.txt, did what the txt thing said
opened the launcher, made the Ram thing about Max, clicked start button
and again it doesn't start the game.
if you got some sort of program(s) that im supposed to install or anything i have to do to fix this issue i'd appreciate it.
i'll wait for response/questions/anything and thanks.

**Comment by Crowfunder** [comment]
Setting RAM to anything over 3GB is not recommended, setting it to max even more so.

**Comment by Ahmedhejazy747** [comment]
my ram isnt that large or something its like 1.87 gb usable
but ill try lowering it from max and see what happens.

**Comment by Ahmedhejazy747** [comment]
it didnt work.

**Comment by Crowfunder** [comment]
Please post your KnightLauncher settings and computer specs (CPU, amount of RAM, etc)

**Comment by Ahmedhejazy747** [comment]
well, here's my pc specs:
CPU: AMD athlon 64 x2 Dual core prossessor 4800+ 2.50 GHz
GPU: ATI (amd) Radeon Xpress 1150
RAM: 2gbs
System: 86x (32) Bits
KnightLauncher settings:
Launcher:
Language: English
File Cleaning: Checked
Create Shortcut: Checked
keep open on launch: Unchecked
Game:
Platform: standalone
alocated RAM: 512 MB
Use a diffrent GC behavior: Unchecked +Paralel Old +  unavailable to check or interact
Disable Explicit GC: unchecked + unavailable to check or interact
Patch a 64-bit Java VM: unavailable to interact
Installed Java VM: Unknown Java 
Advanced:
Server Adress: game.spiralknights.com Port: 47624
Public Key: a5ed0dc3892b9472cfb668e236064e989e95945dad18f3d7e7d8e474d6e03de38bc044c3429b9ca649d0881d601c0eb8ffebc3756f0503f73a8ca1760943ea0e8921ad6f8102026586db3133844bbadbcfcfc666d23982d7684511fbf6cd8bb1d02a14270d0854098d16fe88f99c05825b0fe1b6fd497709106f2c418796aaf7aab7c92f26fcd9fbb3c43df48075fed8dd931273a7b0a333c8de5967797874c1944aed65b47f0792b273a529ac22a2dce08dad04eeebeeff67c7bc99b97682bff488038b28e24f4b5eea77ed966caede52f2c1ecf2b403110a9765daa81ddf718129a040823bead3a0bdca70ef6d08f483757a6d3b6e01fbbcb32006b7872bcd#10001
GetDown URL:http://gamemedia2.spiralknights.com/spiral/client/
That was all my pc specs and Knightlauncher settings.

**Comment by Crowfunder** [comment]
Your system is 32bit, whereas KnightLauncher patches 64bit java incompatible with your system. Moreso your specs are like really low so I doubt KL can help with anything here.
